name: Format Code

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  token: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install dependencies
        run: deno install --allow-scripts

      - name: Format Code
        run: |
          deno fmt

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -am "chore: format code" || true
          git push
